services:
  app:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: flask --app api run --host=0.0.0.0 --port=8000 --reload
    environment:
      FLASK_APP: app.py
    networks:
      - name_project_network
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: name_db
    ports:
      - "3306:3306"
    volumes:
      - name_db_db:/var/lib/mysql
    networks:
      - name_db_network

volumes:
  name_project_backend:
  name_project_db:

networks:
  name_project_network:
    driver: bridge